dir: "{{.InterfaceDirRelative}}"
inpackage: true
filename: "mock_{{.InterfaceNameSnake}}.go"
mock-build-tags: "!release"
disable-version-string: true
packages:
  log/slog:
    interfaces:
      Handler:
        config:
          inpackage: false
          outpkg: 'diag'
          dir: 'pkg/diag'
          filename: "mock_slog_handler.go"
          mockname: MockSlogHandler
  github.com/gemyago/top-k-system-go/pkg/app/ingestion:
    interfaces:
      Commands:
  github.com/gemyago/top-k-system-go/pkg/services:
    interfaces:
      KafkaWriter: