dir: "{{.InterfaceDirRelative}}"
inpackage: true
filename: "mock_{{.InterfaceNameSnake}}.go"
mock-build-tags: "!release"
disable-version-string: true
packages:
  log/slog:
    interfaces:
      Handler:
        config:
          inpackage: false
          outpkg: 'diag'
          dir: 'pkg/diag'
          filename: "mock_slog_handler.go"
          mockname: MockSlogHandler
  github.com/gemyago/top-k-system-go/internal/app/ingestion:
    config:
      filename: "{{.InterfaceNameSnake}}.go"
      mockname: "{{ .InterfaceName | camelcase }}"
    interfaces:
      mockCommands:
  github.com/gemyago/top-k-system-go/internal/app/aggregation:
    config:
      mockname: "mock{{ .InterfaceName | camelcase }}"
    interfaces:
      mockCommands:
        config:
          mockname: "{{ .InterfaceName | camelcase }}"
          filename: "{{.InterfaceNameSnake}}.go"
      countersFactory:
      counters:
      checkPointer:
      checkPointerModel:
      itemEventsAggregator:
      itemEventsAggregatorModel:
  github.com/gemyago/top-k-system-go/internal/services:
    config:
      filename: "{{.InterfaceNameSnake}}.go"
      mockname: "{{ .InterfaceName | camelcase }}"
    interfaces:
      mockKafkaWriter:
      mockKafkaReader:
  github.com/gemyago/top-k-system-go/internal/services/blobstorage:
    interfaces:
      Storage: