apiVersion: v1
kind: PersistentVolume
metadata:
  name: blobs-storage
spec:
  storageClassName: local-path
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /var/lib/blobs-storage
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: blobs-storage
spec:
  storageClassName: local-path
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi