apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ .Values.app.name }}-checkpointer
spec:
  # every 15 minutes
  schedule: "*/15 * * * *"
  jobTemplate:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      parallelism: 1
      template:
        spec:
          containers:
            - name: checkpointer
              image: "{{ .Values.image.ref }}"
              imagePullPolicy: {{ .Values.image.pullPolicy }}
              command:
                - checkpointer
                - create-check-point
              env:
                - name: APP_HTTPSERVER_PORT
                  value: "{{ .Values.service.port }}"
                - name: APP_ENV
                  value: "{{ .Values.app.env }}"
                {{- with .Values.env }}
                {{- toYaml . | nindent 16 }}
                {{- end }}
              resources:
                {{- toYaml .Values.resources | nindent 16 }}
              {{- with .Values.volumeMounts }}
              volumeMounts:
                {{- toYaml . | nindent 16 }}
              {{- end }}
          restartPolicy: OnFailure
          {{- with .Values.volumes }}
          volumes:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.nodeSelector }}
          nodeSelector:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.affinity }}
          affinity:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.tolerations }}
          tolerations:
            {{- toYaml . | nindent 12 }}
          {{- end }}

