// Code generated by mockery. DO NOT EDIT.

//go:build !release

package blobstorage

import (
	context "context"
	io "io"

	mock "github.com/stretchr/testify/mock"
)

// MockStorage is an autogenerated mock type for the Storage type
type MockStorage struct {
	mock.Mock
}

type MockStorage_Expecter struct {
	mock *mock.Mock
}

func (_m *MockStorage) EXPECT() *MockStorage_Expecter {
	return &MockStorage_Expecter{mock: &_m.Mock}
}

// Download provides a mock function with given fields: ctx, key, out
func (_m *MockStorage) Download(ctx context.Context, key string, out io.Writer) error {
	ret := _m.Called(ctx, key, out)

	if len(ret) == 0 {
		panic("no return value specified for Download")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, io.Writer) error); ok {
		r0 = rf(ctx, key, out)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockStorage_Download_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Download'
type MockStorage_Download_Call struct {
	*mock.Call
}

// Download is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
//   - out io.Writer
func (_e *MockStorage_Expecter) Download(ctx interface{}, key interface{}, out interface{}) *MockStorage_Download_Call {
	return &MockStorage_Download_Call{Call: _e.mock.On("Download", ctx, key, out)}
}

func (_c *MockStorage_Download_Call) Run(run func(ctx context.Context, key string, out io.Writer)) *MockStorage_Download_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(io.Writer))
	})
	return _c
}

func (_c *MockStorage_Download_Call) Return(_a0 error) *MockStorage_Download_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockStorage_Download_Call) RunAndReturn(run func(context.Context, string, io.Writer) error) *MockStorage_Download_Call {
	_c.Call.Return(run)
	return _c
}

// Upload provides a mock function with given fields: ctx, key, contents
func (_m *MockStorage) Upload(ctx context.Context, key string, contents io.Reader) error {
	ret := _m.Called(ctx, key, contents)

	if len(ret) == 0 {
		panic("no return value specified for Upload")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, io.Reader) error); ok {
		r0 = rf(ctx, key, contents)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockStorage_Upload_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Upload'
type MockStorage_Upload_Call struct {
	*mock.Call
}

// Upload is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
//   - contents io.Reader
func (_e *MockStorage_Expecter) Upload(ctx interface{}, key interface{}, contents interface{}) *MockStorage_Upload_Call {
	return &MockStorage_Upload_Call{Call: _e.mock.On("Upload", ctx, key, contents)}
}

func (_c *MockStorage_Upload_Call) Run(run func(ctx context.Context, key string, contents io.Reader)) *MockStorage_Upload_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(io.Reader))
	})
	return _c
}

func (_c *MockStorage_Upload_Call) Return(_a0 error) *MockStorage_Upload_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockStorage_Upload_Call) RunAndReturn(run func(context.Context, string, io.Reader) error) *MockStorage_Upload_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockStorage creates a new instance of MockStorage. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockStorage(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockStorage {
	mock := &MockStorage{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
