// Code generated by mockery. DO NOT EDIT.

//go:build !release

package aggregation

import mock "github.com/stretchr/testify/mock"

// mockCounters is an autogenerated mock type for the counters type
type mockCounters struct {
	mock.Mock
}

type mockCounters_Expecter struct {
	mock *mock.Mock
}

func (_m *mockCounters) EXPECT() *mockCounters_Expecter {
	return &mockCounters_Expecter{mock: &_m.Mock}
}

// getItemsCounters provides a mock function with given fields:
func (_m *mockCounters) getItemsCounters() map[string]int64 {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for getItemsCounters")
	}

	var r0 map[string]int64
	if rf, ok := ret.Get(0).(func() map[string]int64); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]int64)
		}
	}

	return r0
}

// mockCounters_getItemsCounters_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'getItemsCounters'
type mockCounters_getItemsCounters_Call struct {
	*mock.Call
}

// getItemsCounters is a helper method to define mock.On call
func (_e *mockCounters_Expecter) getItemsCounters() *mockCounters_getItemsCounters_Call {
	return &mockCounters_getItemsCounters_Call{Call: _e.mock.On("getItemsCounters")}
}

func (_c *mockCounters_getItemsCounters_Call) Run(run func()) *mockCounters_getItemsCounters_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *mockCounters_getItemsCounters_Call) Return(_a0 map[string]int64) *mockCounters_getItemsCounters_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *mockCounters_getItemsCounters_Call) RunAndReturn(run func() map[string]int64) *mockCounters_getItemsCounters_Call {
	_c.Call.Return(run)
	return _c
}

// getLastOffset provides a mock function with given fields:
func (_m *mockCounters) getLastOffset() int64 {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for getLastOffset")
	}

	var r0 int64
	if rf, ok := ret.Get(0).(func() int64); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(int64)
	}

	return r0
}

// mockCounters_getLastOffset_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'getLastOffset'
type mockCounters_getLastOffset_Call struct {
	*mock.Call
}

// getLastOffset is a helper method to define mock.On call
func (_e *mockCounters_Expecter) getLastOffset() *mockCounters_getLastOffset_Call {
	return &mockCounters_getLastOffset_Call{Call: _e.mock.On("getLastOffset")}
}

func (_c *mockCounters_getLastOffset_Call) Run(run func()) *mockCounters_getLastOffset_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *mockCounters_getLastOffset_Call) Return(_a0 int64) *mockCounters_getLastOffset_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *mockCounters_getLastOffset_Call) RunAndReturn(run func() int64) *mockCounters_getLastOffset_Call {
	_c.Call.Return(run)
	return _c
}

// updateItemsCount provides a mock function with given fields: lastOffset, increments
func (_m *mockCounters) updateItemsCount(lastOffset int64, increments map[string]int64) {
	_m.Called(lastOffset, increments)
}

// mockCounters_updateItemsCount_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'updateItemsCount'
type mockCounters_updateItemsCount_Call struct {
	*mock.Call
}

// updateItemsCount is a helper method to define mock.On call
//   - lastOffset int64
//   - increments map[string]int64
func (_e *mockCounters_Expecter) updateItemsCount(lastOffset interface{}, increments interface{}) *mockCounters_updateItemsCount_Call {
	return &mockCounters_updateItemsCount_Call{Call: _e.mock.On("updateItemsCount", lastOffset, increments)}
}

func (_c *mockCounters_updateItemsCount_Call) Run(run func(lastOffset int64, increments map[string]int64)) *mockCounters_updateItemsCount_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(int64), args[1].(map[string]int64))
	})
	return _c
}

func (_c *mockCounters_updateItemsCount_Call) Return() *mockCounters_updateItemsCount_Call {
	_c.Call.Return()
	return _c
}

func (_c *mockCounters_updateItemsCount_Call) RunAndReturn(run func(int64, map[string]int64)) *mockCounters_updateItemsCount_Call {
	_c.Call.Return(run)
	return _c
}

// newMockCounters creates a new instance of mockCounters. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockCounters(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockCounters {
	mock := &mockCounters{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
