name: Tests

on: 
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - 'main'

jobs:
  run-tests:
    name: Run
    runs-on: ubuntu-24.04
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - uses: actions/setup-go@v5
      with:
        go-version-file: 'go.mod'
        cache-dependency-path: 'go.sum'

    - id: golangci-version
      name: Get golangci version
      run: echo "value=$(cat .golangci-version)" >> $GITHUB_OUTPUT

    - name: lint
      uses: golangci/golangci-lint-action@v6
      with:
        version: '${{ steps.golangci-version.outputs.value }}'

    - run: make test

    - name: Store Test Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: test-artifacts-pr-${{ github.event.pull_request.node_id }}
        path: |
          .cover/coverage.svg
          .cover/coverage.html
        retention-days: 10
        overwrite: true